### ISSUE TITLE
Access URL for hyku-beta docker container?

### ISSUE THREAD

**Issue by jmignault** [samvera/hyku#1080] opened 2017-05-09 17:20 UTC
I am running the docker container, which built fine. I cannot find the URL to access the container. Attempting to access port 8080 on the host results in a 404. I have done some searching of the documentation and found nothing regarding this.

**Comment by cbeer** [comment] 2017-05-09 17:24
You should be able to access the site at one of:

- the value of `Settings.multitenancy.admin_host` (unset by default; you can either set it in the settings file, or by setting the `SETTINGS__MULTITENANCY__ADMIN_HOST` variable
- `ENV['HOST']` (likely unset by default in the container, but you can probably pass it in?)
- `http://localhost:8080/`

(it occurs to me, you might need to whitelist those env variables in https://github.com/projecthydra-labs/hyku/blob/master/docker-compose.yml#L106.. not sure though)

**Comment by jmignault** [comment] 2017-05-09 18:51
Thanks. The localhost URL is working. I could've sworn I tried that. Still, the beta docs simply list the docker-compose command with no indication of what to do next.

**Comment by jmignault** [comment] 2017-05-15 20:21
Perhaps the explanation @cbeer gave above, with explanation of how and where to set the envvars. I swear to God that when I first got the container running, attempting to access http://localhost:8080 gave me a 404. It works now, though. But a bit more explanation could be helpful.

**Comment by jmignault** [comment] 2017-05-16 13:46
I'm adding these instructions to ```README.md``` in preparation for a pull request and I have a couple questions:
+ @cbeer refers to the settings file above; what file is that specifically?
+ Also how would one pass in the ```ENV['HOST']``` variable? On the docker-compose command-line preceding the command?

**Comment by mjgiarlo** [comment] 2017-05-31 21:03
@jmignault Sorry this fell through the cracks! Answers:

* That file is `config/settings.yml`
* It looks like Docker supports a `-e` flag, so `your_docker_command_here -e HOST='your_value_here'`

**Comment by jmignault** [comment] 2017-06-05 17:28
@mjgiarlo Thanks for the file name. When bringing the containers back up using 

`docker-compose up -d`

the -e switch is not accepted. Is there a different command I should be using?

**Comment by mjgiarlo** [comment] 2017-06-05 18:18
@jmignault I'm not sure, but I can confirm that you're right about `-e` not being accepted by `docker-compose up`. There are multiple options documented here: https://docs.docker.com/compose/environment-variables/

**Comment by lpmagnuson** [comment] 2017-07-24 19:55
@jmignault / @mjgiarlo  - did you ever find the solution to this problem? I am having a similar issue.  I'm running Hyku via Docker on Amazon Lightsail.  The containers are running, public site loads great on localhost (I can tell by running curl localhost:8080 from terminal when connected to the server), but my attempts to link my public static IP to the running instance have failed so far.  When attempting to load the site via my public static IP address or the hostname linked to the static IP, I get a rails 404 error using port :8080.  I have tried:

- editing config/settings.yml so that multitenancy: enabled: true and admin_host is my static public IP address;

- adding an extra_hosts section to the web service and the fcrepo service in docker-compose.yml that looks like this:

```
extra_hosts:
- "example.org:x.x.x.x"
```

Where example.org is the hostname I have linked to the static IP in Amazon Lightsail config.

Despite running docker-compose up -d several times to restart after changing settings, I'm still getting success on localhost:8080 but a 404 on both my public IP and my hostname.

Would definitely love other suggestions - I need to have this accessible via browser for testing, as we're running this test for a consortia that will be accessing the site remotely. If there's some more documentation I should be looking at or if you have suggestions of where in my system logs I can look for insight, please do let me know!

**Comment by mjgiarlo** [comment] 2017-07-24 22:06
Any thoughts on the above comment by @lpmagnuson, @eefahy @bbranan @cbeer @jcoyne?

**Comment by bbranan** [comment] 2017-07-25 13:10
@lpmagnuson I haven't tried running Hyku with Lightsail, but given that the site is available on localhost:8080, you'll need to look at how traffic is being routed (or not, in this case) to your instance. I would look first at the security group(s) attached to the instance to verify that ports 80 and 8080 are open. If Lightsail makes use of a load balancer, make sure the listeners are pointing traffic to port 8080. You may also want to open a support ticket with AWS, as they'll be able to look directly at the instances to see what may be hanging things up.

**Comment by lpmagnuson** [comment] 2017-07-26 19:56
Thanks @bbranan.  Ports 80 and 8080 are open, and when I run just sudo docker-compose up and watch for output while I connect via browser to my assigned static ip with port 8080, I see the 404 error in the browser and the docker output logs the fact that a rails 404 was delivered (see attached logs). 
[web_1_output.txt](https://github.com/samvera-labs/hyku/files/1177875/web_1_output.txt)

I'm wondering if there's something I need to do in docker-compose to bridge the running instance on localhost with my static IP that's externally facing.  It appears that my static IP is not pointing correctly to the docker instances - it's pointing to something because it's serving a rails 404, but not routing properly to what's able to load up on localhost.  curl localhost:8080 is still returning the correct Hyku welcome page. 

I noticed in docker-compose.yml there are blank settings for networks, which I can see are defined when I run `sudo docker network ls` (hyku_external and hyku_internal).  Should I configure these networks to use my internal and external static IPs, or am I totally misinterpreting what those network definitions are for?   I've been going through the docs on docker networks and bridges and admit I'm a bit lost.  Any pointers would be helpful. 

Thanks so much for any help!

Lauren

**Comment by lpmagnuson** [comment] 2017-07-27 03:49
OK, I know what's happening now, though I still am not sure how to fix it.  I noticed that the 404 error page being served up by my public static IP is not the same error page within my installed hyku repository code (/home/user/hyku/public/404.html).  I know this because if I edit that page, no change occurs in the 404 page that loads in my browser via my public static IP.

I dug around on the server and figured out that the 404 being served up is located here:

/var/lib/docker/aufs/diff/ef5e47f320275bc37360adcb4b44ef703a69d651999d903a453db5fee8a4c4cc/data/public/404.html

Editing this file produces the expected changes via the public IP.

From what I (very tenuously) understand about docker, images in the 'diff' directory is meant to be a sort of backup (?) image.  I dug around for some advice and tried to clean up some old diff images, but that actually ended up breaking even my ability to access my hyku app on localhost.

I realize that my questions here are just total docker n00b questions, so sorry to bug about this, but any pointers in the right direction would be appreciated!  From the output when I ran sudo docker-compose up, it looked like this particular data directory was created through that process, but I have a very limited understanding of how or why this particular docker image was created or why my attempts to access my server via public IP would be routing to it.

Thanks!

Lauren

**Comment by orangewolf** [comment] 2019-05-05 18:29
@lpmagnuson I think this is fixed by the newly updated docker configuration. There were issues before where the docker-compose was targeted more toward production deploy and caused lots of problems with people trying to use it for dev.  The new config separates docker-compose.yml and docker-compose.production.yml so there are fewer compromises that have to be made and that things like caching of containers vs serving locally synced files can be more correctly done.  Can you try it out and reopen this issue if you are still having an issue? (I know this is old, so "I'm over it" is also a reasonable outcome ;-)

**Closed by orangewolf** 2019-05-05 18:29 UTC
Labels: docker, documentation
